<link rel="stylesheet" type="text/css" href="/assets/form_assets/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/fonts/iconic/css/material-design-iconic-font.min.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/vendor/animate/animate.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/vendor/css-hamburgers/hamburgers.min.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/vendor/animsition">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/vendor/daterangepicker/daterangepicker.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/css/util.css">
<link rel="stylesheet" type="text/css" href="/assets/form_assets/css/main.css">